name: CD

on:
  push:
    branches:
      - main
      - release

jobs:
  cd-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Run tests with Maven
        run: mvn -B -f pom.xml test jacoco:prepare-agent jacoco:report


      - name: Build application with Maven
        run: mvn -B -f pom.xml clean install -Dmaven.test.skip=true

      - name: Deploy to Homolog
        run: |
          # Comandos para realizar o deploy na máquina de homologação na Azure
    
  cd-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17' # substitua pela versão desejada do JDK

      - name: Run tests with Maven
        run: mvn -B -f pom.xml test jacoco:prepare-agent jacoco:report

      - name: SonarQube Scan
        run: mvn -B sonar:sonar -Dsonar.organization=your_organization -Dsonar.projectKey=your_project_key
        env:
          GGITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          run: |
            mvn -B verify sonar:sonar \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=MatteusP \
            -Dsonar.projectkey=MatteusP_java-api \
            -Dsonar.languange=java \
            -Dsonar.java.coveragePlugin=janoco \
            -Dmaven.test.skip=true

      - name: Build application with Maven
        run: mvn -B -f pom.xml clean install -Dmaven.test.skip=true

      - name: Deploy to Prod
        run: |
      
