name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  CI:
  runs-on: ubuntu-latest
      
steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up JDK 17
  uses: actions/setup-java@v3
  with:
    java-version: '17'
    distribution: 'corretto'
    cache: maven
        
      - name: Run the tests
        run: mvn -B -f pom.xml test jacoco:prepare-agent jacoco:report
        env:
          CI: true
          
      - name: SonarCloud Analyze
  env:
    GGITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  run: |
    mvn -B verify sonar:sonar \
    -Dsonar.host.url=https://sonarcloud.io \
    -Dsonar.organization=MatteusP \
    -Dsonar.projectkey=MatteusP_java-api \
    -Dsonar.languange=java \
    -Dsonar.java.coveragePlugin=janoco \
    -Dmaven.test.skip=true
