
name: "CI"

on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - main
    
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set UP JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "corretto"
          cache: maven

      - name: Testes Maven
        run: mvn -B -f pom.xml test jacoco:prepare-agent jacoco:report

      - name: SonarCloud Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GGITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B verify sonar:sonar \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=matteusp \
          -Dsonar.projectKey=MatteusP_Hackathon \
          -Dorganization-key=ligtonribeiro \
          -Dsonar.language=java \
          -Dsonar.java.coveragePlugin=jacoco \
          -Dmaven.test.skip=true
